### ISSUE TITLE
Some processes crashing with {:error, :no_leader}

### ISSUE THREAD

**Issue by liveforeverx** [skirino/raft_kv#3]
Seems like there some process crashing, I didn't checked the reason why, but the raft_kv otherwise works (I can update / read values from it):

```elixir
19:55:13.492 [error] GenServer #PID<0.1070.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout

19:56:06.848 [error] GenServer RaftKV.EtsRecordManager terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv.ex:84: RaftKV.list_keyspaces/0
    (raft_kv) lib/raft_kv/ets_record_manager.ex:47: RaftKV.EtsRecordManager.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
```

**Comment by liveforeverx** [comment]
Test environment, 3 node cluster, locally without simulated failures. Probably will investigate later this week.

**Comment by skirino** [comment]
Both `StatsReporter` and `EtsRecordManager` are stateless `GenServer`s; they should be fine after supervisor restart.
So the problem here should be `:no_leader` of `RaftKV.Keyspaces` consensus group.

Raft leader process steps down when the leader and majority of followers cannot communicate in a timely fashion.
And communications can be delayed by various factors such as CPU contention, network bandwidth contention, disk contention (if you persist the consensus group state).

**Comment by liveforeverx** [comment]
@skirino It happen on a local machine, Macbook in a 3 cluster setup, so no persistence.

Seems, like I can exclude network bandwidth contention, disk contention.

I do nothing in application (means, no load, so it is idle) and I see:

```elixir
08:05:02.405 [error] GenServer #PID<0.1208.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout

08:06:06.410 [error] GenServer #PID<0.1223.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout

08:07:10.416 [error] GenServer #PID<0.1237.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
```

Means, every minute and 5 seconds the process crashes... I traced the function: 

```
#PID<0.1325.0> call RaftKV.Keyspaces.submit_stats(%{db_cache: %{0 => {3, 0, 0, 0}}, registry_cache: %{0 => {0, 0, 0, 0}}})
#PID<0.1325.0> [4004ms] exception RaftKV.Keyspaces.submit_stats/1 -> :error:{:badmatch, {:error, :no_leader}}
iex(dev3@dar)16>
08:12:30.449 [error] GenServer #PID<0.1325.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
#PID<0.1344.0> call RaftKV.Keyspaces.submit_stats(%{db_cache: %{0 => {3, 0, 0, 0}}, registry_cache: %{0 => {0, 0, 0, 0}}})
#PID<0.1344.0> [4005ms] exception RaftKV.Keyspaces.submit_stats/1 -> :error:{:badmatch, {:error, :no_leader}}
iex(dev3@dar)16>
08:13:34.457 [error] GenServer #PID<0.1344.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
#PID<0.1358.0> call RaftKV.Keyspaces.submit_stats(%{db_cache: %{0 => {3, 0, 0, 0}}, registry_cache: %{0 => {0, 0, 0, 0}}})
#PID<0.1358.0> [4004ms] exception RaftKV.Keyspaces.submit_stats/1 -> :error:{:badmatch, {:error, :no_leader}}
iex(dev3@dar)16>
08:14:38.464 [error] GenServer #PID<0.1358.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
```

It never succeed, so it is a consistent, not temporary problem.

In the same time, I checked the kv functionality and it works...

**Comment by skirino** [comment]
Key-value data operation should work as they don't directly depend on `Keyspaces` consensus group; `Keyspaces` is for maintaining metadata.

Inspect the internal of `Keyspaces` consensus group by evaluating `RaftedValue.status(RaftKV.Keyspaces)` in each node.
Adjusting timeout values using `RaftedValue.change_config/2` might help.

**Comment by liveforeverx** [comment]
```elixir
iex(dev1@dar)4> RaftedValue.status RaftKV.Keyspaces
%{
  config: %RaftedValue.Config{
    communication_module: RaftedValue.RemoteMessageGateway,
    data_module: RaftKV.Keyspaces,
    election_timeout: 2000,
    election_timeout_clock_drift_margin: 1000,
    heartbeat_timeout: 1000,
    leader_hook_module: RaftKV.Keyspaces.Hook,
    max_retained_command_results: 100
  },
  current_term: 0,
  from: #PID<0.1009.0>,
  leader: #PID<0.1009.0>,
  members: [#PID<31449.1003.0>, #PID<0.1009.0>],
  state_name: :leader,
  unresponsive_followers: []
}
iex(dev1@dar)5>
11:29:13.485 [error] GenServer #PID<0.596.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout

11:30:17.491 [error] GenServer #PID<0.1166.0> terminating
** (MatchError) no match of right hand side value: {:error, :no_leader}
    (raft_kv) lib/raft_kv/keyspaces.ex:358: RaftKV.Keyspaces.submit_stats/1
    (raft_kv) lib/raft_kv/stats_reporter.ex:20: RaftKV.StatsReporter.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :timeout
RaftedValue.status RaftKV.Keyspaces
** (exit) exited in: :gen_statem.call(RaftKV.Keyspaces, :status, {:dirty_timeout, 5000})
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (stdlib) gen.erl:228: :gen.do_for_proc/2
    (stdlib) gen_statem.erl:598: :gen_statem.call_dirty/4
```

They were there, than they stoped (didn't checked the reason, but it's not printed), than they are not there.

**Comment by liveforeverx** [comment]
Every node, which starts to print this message, doesn't have a rafted process anymore.

**Comment by skirino** [comment]
What do you mean by "rafted process"?
I have no idea how to reproduce.
Could you try to `Process.monitor` the `Keyspaces` process in all nodes and get the `reason` for termination?

By the way, why do you always use "than" for "then"? Just please **never** do it again.

**Comment by liveforeverx** [comment]
Reason for a crash found, will check, if it solves completely.

**Comment by liveforeverx** [comment]
Fixed.
